"""v6_schema

Revision ID: 0529c0f5a20c
Revises: 757512b30689
Create Date: 2026-04-21 13:56:29.116780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0529c0f5a20c'
down_revision: Union[str, Sequence[str], None] = '757512b30689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimens', sa.Column('season', sa.String(length=10), nullable=True))
    op.add_column('specimens', sa.Column('result_type', sa.String(length=20), nullable=True))
    op.add_column('specimens', sa.Column('predicted_sex', sa.String(length=10), nullable=True))
    op.add_column('specimens', sa.Column('predicted_male_form', sa.String(length=15), nullable=True))
    op.add_column('specimens', sa.Column('top3_json', sa.Text(), nullable=True))
    op.add_column('specimens', sa.Column('preprocessing_mode', sa.String(length=20), nullable=True))
    op.add_column('specimens', sa.Column('label_level', sa.Integer(), nullable=True))
    op.create_index('idx_spec_label_level', 'specimens', ['label_level'], unique=False)
    op.create_index('idx_spec_result_type', 'specimens', ['result_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_spec_result_type', table_name='specimens')
    op.drop_index('idx_spec_label_level', table_name='specimens')
    op.drop_column('specimens', 'label_level')
    op.drop_column('specimens', 'preprocessing_mode')
    op.drop_column('specimens', 'top3_json')
    op.drop_column('specimens', 'predicted_male_form')
    op.drop_column('specimens', 'predicted_sex')
    op.drop_column('specimens', 'result_type')
    op.drop_column('specimens', 'season')
    # ### end Alembic commands ###
