"""init

Revision ID: 757512b30689
Revises: 
Create Date: 2026-04-20 17:48:54.306525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757512b30689'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('specimen_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=16), nullable=True),
    sa.Column('image_hash', sa.String(length=16), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_grid', sa.String(length=32), nullable=True),
    sa.Column('predicted_species', sa.String(length=80), nullable=True),
    sa.Column('predicted_confidence', sa.Float(), nullable=True),
    sa.Column('predicted_calibrated_confidence', sa.Float(), nullable=True),
    sa.Column('is_ood', sa.Boolean(), nullable=True),
    sa.Column('ood_score', sa.Float(), nullable=True),
    sa.Column('user_corrected', sa.Boolean(), nullable=True),
    sa.Column('correct_species', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('male_form', sa.String(length=15), nullable=True),
    sa.Column('is_trainable', sa.Boolean(), nullable=True),
    sa.Column('label_source', sa.String(length=20), nullable=True),
    sa.Column('admin_status', sa.String(length=20), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('admin_reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('admin_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spec_admin', 'specimens', ['admin_status'], unique=False)
    op.create_index('idx_spec_session', 'specimens', ['session_id'], unique=False)
    op.create_index('idx_spec_trainable', 'specimens', ['is_trainable', 'label_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_spec_trainable', table_name='specimens')
    op.drop_index('idx_spec_session', table_name='specimens')
    op.drop_index('idx_spec_admin', table_name='specimens')
    op.drop_table('specimens')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
